jobs:
  component:
    image: node:8
    requires: [~pr, ~commit]
    steps:
      - sleep: sleep 1
  component-2:
    image: node:8
    requires: [~pr, ~commit]
    steps:
      - sleep: sleep 1
  component-3:
    image: node:8
    requires: [~pr, ~commit]
    steps:
      - sleep: sleep 1
  component-4:
    image: node:8
    requires: [~pr, ~commit]
    steps:
      - sleep: sleep 1
  component-1-1:
    image: node:8
    requires: [component]
    steps:
      - sleep: sleep 1
  component-1-2:
    image: node:8
    requires: [component-1-1]
    steps:
      - sleep: sleep 1
  component-1-3:
    image: node:8
    requires: [component-1-2]
    steps:
      - sleep: sleep 1
  component-1-4:
    image: node:8
    requires: [component-1-3]
    steps:
      - sleep: sleep 1
